server:
  port: 8080

spring:
  application:
    name: adapter-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    root: INFO
    com.example.adapter: DEBUG